version: 2

project_name: aiscan

before:
  hooks:
    - go generate ./pkg/tools/resources

builds:
  - id: aiscan
    main: ./cmd/aiscan
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    tags:
      - forceposix
      - emptytemplates
      - noembed
      - osusergo
      - netgo
    ldflags:
      - -s -w
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}

  - id: acp
    main: ./cmd/acp
    binary: "acp"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    tags:
      - forceposix
      - osusergo
      - netgo
    ldflags:
      - -s -w
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}

upx:
  - enabled: true
    goos: [linux, windows]
    goarch:
      - amd64

archives:
  - id: aiscan
    builds: [aiscan]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - binary

  - id: acp
    builds: [acp]
    name_template: "acp_{{ .Os }}_{{ .Arch }}"
    formats:
      - binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: desc
  filters:
    exclude:
      - '^MERGE'
      - "{{ .Tag }}"
      - "^docs"

release:
  github:
    owner: chainreactors
    name: aiscan
  draft: true
  prerelease: auto
  replace_existing_draft: true
  replace_existing_artifacts: true
  mode: replace
  name_template: "{{ .Tag }}"
