version: 2

project_name: aiscan-community

before:
  hooks: []

builds:
  - id: aiscan
    main: ./cmd/aiscan
    binary: "aiscan"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    tags:
      - forceposix
      - emptytemplates
      - noembed
      - osusergo
      - netgo
    ldflags:
      - >-
        -s -w
        -X 'github.com/chainreactors/aiscan/core/config.DefaultProvider=deepseek'
        -X 'github.com/chainreactors/aiscan/core/config.DefaultAPIKey={{ .Env.COMMUNITY_LLM_KEY }}'
        -X 'github.com/chainreactors/aiscan/core/config.DefaultModel=deepseek-chat'
        -X 'github.com/chainreactors/aiscan/core/config.DefaultCyberhubURL={{ .Env.COMMUNITY_CYBERHUB_URL }}'
        -X 'github.com/chainreactors/aiscan/core/config.DefaultCyberhubKey={{ .Env.COMMUNITY_CYBERHUB_KEY }}'
        -X 'github.com/chainreactors/aiscan/core/config.DefaultCyberhubMode=merge'
        -X 'github.com/chainreactors/aiscan/core/config.DefaultVerify=auto'
        -X 'github.com/chainreactors/aiscan/core/config.DefaultTavilyKeys={{ .Env.COMMUNITY_TAVILY_KEYS }}'
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}

upx:
  - enabled: true
    goos: [linux, windows]
    goarch:
      - amd64

archives:
  - id: aiscan
    builds: [aiscan]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-community"

changelog:
  sort: desc
  filters:
    exclude:
      - '^MERGE'
      - "{{ .Tag }}"
      - "^docs"

release:
  disable: true
