// Code generated by templates_gen.go; DO NOT EDIT.

package resources

import (
	_ "embed"

	"github.com/chainreactors/utils/encode"
)

//go:embed data/http.bin
var httpData []byte

//go:embed data/socket.bin
var socketData []byte

//go:embed data/fingerprinthub_web.bin
var fingerprinthubWebData []byte

//go:embed data/fingerprinthub_service.bin
var fingerprinthubServiceData []byte

//go:embed data/port.bin
var portData []byte

//go:embed data/extract.bin
var extractData []byte

//go:embed data/workflow.bin
var workflowData []byte

//go:embed data/neutron.bin
var neutronData []byte

//go:embed data/spray_rule.bin
var sprayRuleData []byte

//go:embed data/spray_dict.bin
var sprayDictData []byte

//go:embed data/spray_common.bin
var sprayCommonData []byte

//go:embed data/zombie_common.bin
var zombieCommonData []byte

//go:embed data/zombie_default.bin
var zombieDefaultData []byte

//go:embed data/zombie_rule.bin
var zombieRuleData []byte

//go:embed data/zombie_template.bin
var zombieTemplateData []byte

//go:embed data/found_keys.bin
var foundKeysData []byte

//go:embed data/found_spray.bin
var foundSprayData []byte

//go:embed data/found_filter_ext.bin
var foundFilterExtData []byte

//go:embed data/found_filter_dir.bin
var foundFilterDirData []byte

func loadEmbeddedConfig(typ string) []byte {
	if typ == "http" {
		return encode.MustDeflateDeCompress(httpData)
	}
	if typ == "socket" {
		return encode.MustDeflateDeCompress(socketData)
	}
	if typ == "fingerprinthub_web" {
		return encode.MustDeflateDeCompress(fingerprinthubWebData)
	}
	if typ == "fingerprinthub_service" {
		return encode.MustDeflateDeCompress(fingerprinthubServiceData)
	}
	if typ == "port" {
		return encode.MustDeflateDeCompress(portData)
	}
	if typ == "extract" {
		return encode.MustDeflateDeCompress(extractData)
	}
	if typ == "workflow" {
		return encode.MustDeflateDeCompress(workflowData)
	}
	if typ == "neutron" {
		return encode.MustDeflateDeCompress(neutronData)
	}
	if typ == "spray_rule" {
		return encode.MustDeflateDeCompress(sprayRuleData)
	}
	if typ == "spray_dict" {
		return encode.MustDeflateDeCompress(sprayDictData)
	}
	if typ == "spray_common" {
		return encode.MustDeflateDeCompress(sprayCommonData)
	}
	if typ == "zombie_common" {
		return encode.MustDeflateDeCompress(zombieCommonData)
	}
	if typ == "zombie_default" {
		return encode.MustDeflateDeCompress(zombieDefaultData)
	}
	if typ == "zombie_rule" {
		return encode.MustDeflateDeCompress(zombieRuleData)
	}
	if typ == "zombie_template" {
		return encode.MustDeflateDeCompress(zombieTemplateData)
	}
	if typ == "found_keys" {
		return encode.MustDeflateDeCompress(foundKeysData)
	}
	if typ == "found_spray" {
		return encode.MustDeflateDeCompress(foundSprayData)
	}
	if typ == "found_filter_ext" {
		return encode.MustDeflateDeCompress(foundFilterExtData)
	}
	if typ == "found_filter_dir" {
		return encode.MustDeflateDeCompress(foundFilterDirData)
	}
	return nil
}
